const fs = require('fs');
const path = require('path');

const filePath = path.join('e:', 'karsoft', 'mebel', 'src', 'pages', 'orders', 'OrdersCRM.tsx');
let content = fs.readFileSync(filePath, 'utf-8');

// 1. Add imports and hook
content = content.replace("import React, { useState } from 'react';", "import React, { useState } from 'react';\nimport { useTranslation } from 'react-i18next';");
content = content.replace("export const OrdersCRM: React.FC = () => {", "export const OrdersCRM: React.FC = () => {\n  const { t } = useTranslation();");

// 2. Replacements
const rep = {
    "CRM & Буйыртпалар": "{t('orders.title')}",
    "Таза Лид / Буйыртпа Қосыў": "{t('orders.add_lead')}",
    ">Барлық жағдайлар<": ">{t('orders.all_statuses')}<",
    ">Таза Лидлер<": ">{t('orders.new_leads')}<",
    ">Өлшеў Басқышы<": ">{t('orders.measurement_stage')}<",
    ">Дизайн Басқышы<": ">{t('orders.design_stage')}<",
    ">ТТ ҳәм Шәртнамалар<": ">{t('orders.tz_contracts')}<",
    ">Ислеп Шығарыўдағылар<": ">{t('orders.in_production')}<",
    ">Буйыртпалар табылмады.<": ">{t('orders.no_orders')}<",
    ">Мүрәжат Дереги<": ">{t('orders.source')}<",
    ">Лид басқышлары<": ">{t('orders.lead_stages')}<",
    "label: 'Таза Лид'": "label: t('orders.new_lead')",
    "label: 'Өлшеў (Замер)'": "label: t('orders.measurement')",
    "label: '3D Дизайн'": "label: t('orders.design_3d')",
    "label: 'ТТ ҳәм Режелестириў'": "label: t('orders.tz_planning')",
    "label: 'Шәртнама ҳәм Ислеп шығарыў'": "label: t('orders.contract_production')",
    ">Ҳәзирги Басқыш Әмеллери<": ">{t('orders.current_stage_actions')}<",
    ">Қрыйдардың үйин өлшеў ушын өлшеўши (замерщик) бириктириң.<": ">{t('orders.assign_zamerchik_hint')}<",
    ">Өлшеўшини Таңлаң<": ">{t('orders.select_zamerchik')}<",
    ">Өлшеўшини таңлаң<": ">{t('orders.select_zamerchik_placeholder')}<",
    ">Өлшеў Сәнеси ҳәм Ўақты<": ">{t('orders.measurement_date_time')}<",
    "Өлшеўшини Бириктириў <ArrowRight": "{t('orders.assign_zamerchik')} <ArrowRight",
    ">Планшеттен өлшеўши киргизетин анық бөлме өлшемлерин толтырың.<": ">{t('orders.fill_measurement_hint')}<",
    ">Узынлығы (м)<": ">{t('orders.length_m')}<",
    ">Кеңлиги (м)<": ">{t('orders.width_m')}<",
    ">Бәлентлиги (м)<": ">{t('orders.height_m')}<",
    ">Бөлме Өзгешеликлери<": ">{t('orders.room_features')}<",
    ">Мүйешликлер 90° па?<": ">{t('orders.corners_90')}<",
    ">Газ трубасы бар ма?<": ">{t('orders.gas_pipes')}<",
    ">Суў трубасы бар ма?<": ">{t('orders.water_pipes')}<",
    ">Электр розеткалар бар ма?<": ">{t('orders.electrical_outlets')}<",
    "Өлшеў Мағлыўматларын Жүклеў <ArrowRight": "{t('orders.upload_measurement')} <ArrowRight",
    ">3D дизайнер сызған Рендер ямаса OBJ/GLTF рендер сүўретин жүклең.<": ">{t('orders.upload_design_hint')}<",
    ">3D Рендер Сүўрет Силтемеси<": ">{t('orders.design_link')}<",
    "3D Дизайн Рендерин Жүклеў": "{t('orders.upload_design')}",
    "Дизайнды Қрыйдар Тастыйықлады <Check": "{t('orders.design_approved')} <Check",
    ">Буйыртпа ислеп шығарылыў басланыўы ҳәм таяр болыў (Deadline) сәнелерин режелестириң.<": ">{t('orders.schedule_hint')}<",
    ">Ислеп шығарыў басланыўы<": ">{t('orders.production_start')}<",
    ">Қрыйдарға тапсырыў күни (Deadline)<": ">{t('orders.deadline')}<",
    "ТТ Режени Тастыйықлаў <ArrowRight": "{t('orders.approve_tz')} <ArrowRight",
    ">Шәртнаманы басып шығарың, аванс төлемин қабыл етип активлестириң.<": ">{t('orders.contract_hint')}<",
    ">Шәртнама Жәми Суммасы (UZS)<": ">{t('orders.total_sum')}<",
    ">Аванс Төлеми Суммасы (UZS)<": ">{t('orders.advance_sum')}<",
    ">Төлем Түри<": ">{t('orders.payment_type')}<",
    ">Пластик Карта<": ">{t('orders.card')}<",
    ">Нақ Пул<": ">{t('orders.cash')}<",
    ">Есап-Рақам<": ">{t('orders.bank_transfer')}<",
    "Шәртнама Басып Шығарыў": "{t('orders.print_contract')}",
    "Қол қойыў ҳәм Аванс Қабыл Етиў": "{t('orders.sign_accept')}",
    ">Шәртнама Қол Қойылған ҳәм Активлестирилген<": ">{t('orders.contract_signed')}<",
    ">Жойбар ислеп шығарыў ҳәм конвейер процесслеринде кетпекте.<": ">{t('orders.production_process')}<",
    ">Жәми Баҳасы:<": ">{t('orders.total_price')}<",
    ">Төленген аванс:<": ">{t('orders.paid_advance')}<",
    ">Қалдық төлем:<": ">{t('orders.remaining_payment')}<",
    "Шәртнаманы Қайтадан Басып Шығарыў": "{t('orders.reprint_contract')}",
    ">Жойбар Сызбалары ҳәм Өлшемлери<": ">{t('orders.project_drawings')}<",
    ">Узынлығы<": ">{t('orders.length')}<",
    ">Кеңлиги<": ">{t('orders.width')}<",
    ">Бәлентлиги<": ">{t('orders.height')}<",
    " метр<": " {t('orders.meter')}<",
    ">Мүйешликлер мүйеши (90°):<": ">{t('orders.corners_angle')}<",
    " ? 'Туўры' : 'Тегис емес аўыўлар бар'": " ? t('orders.straight') : t('orders.uneven')",
    ">Газ трубалары:<": ">{t('orders.gas_pipes_label')}<",
    " ? 'Бар (Итибар бериң)' : 'Жоқ'": " ? t('orders.present_warn') : t('orders.absent')",
    ">Суў трубалары ноқаты:<": ">{t('orders.water_pipes_label')}<",
    " ? 'Бар' : 'Жоқ'": " ? t('orders.present') : t('orders.absent')",
    ">Розетка / Электр ноқатлар:<": ">{t('orders.outlets_label')}<",
    ">Тастыйықланған 3D Жойбар Модели<": ">{t('orders.approved_model')}<",
    "alt=\"Мебель 3D рендер\"": "alt={t('orders.render_alt')}",
    ">3D модель жойбары еле жүкленбеген.<": ">{t('orders.no_model')}<",
    ">Өлшемлер жоқ. Алдын өлшеў операциясын орынлаң.<": ">{t('orders.no_measurements')}<",
    ">Буйыртпа таңланбаған.<": ">{t('orders.no_order_selected')}<",
    ">Қрыйдардың Толық Ф.И.О<": ">{t('orders.full_name')}<",
    "placeholder=\"Масалан: Сардор Комилов\"": "placeholder={t('orders.name_placeholder')}",
    ">Телефон Рақами<": ">{t('orders.phone')}<",
    ">Келиў Дереги<": ">{t('orders.source_label')}<",
    ">Телеграм<": ">{t('orders.telegram')}<",
    ">Инстаграм<": ">{t('orders.instagram')}<",
    ">Телефон<": ">{t('orders.phone_call')}<",
    ">Офис (Келиўши)<": ">{t('orders.office_visit')}<",
    ">Күтилип атырған Сумма (UZS)<": ">{t('orders.expected_sum')}<",
    ">Бийкар етиў<": ">{t('orders.cancel')}<",
    "Лид Жаратыў": "{t('orders.create_lead')}",
    "alert(\"Складта жетерли шийки зат жоқ! Алдын склад қалдықларын тексериң ямаса товар кирим етиң.\");": "alert(t('orders.alert_no_materials'));",
    "label: 'Өлшеўши Бириктирилди'": "label: t('orders.status_zamer_assigned')",
    "label: 'Өлшеў Орынланды'": "label: t('orders.status_zamer_done')",
    "label: '3D Дизайнда'": "label: t('orders.status_3d')",
    "label: 'Дизайн Тастыйықланды'": "label: t('orders.status_design_approved')",
    "label: 'Реже/ТТ Дүзилди'": "label: t('orders.status_tz_done')",
    "label: 'Шәртнама Қол Қойылды'": "label: t('orders.status_contract_signed')",
    "label: 'Ислеп Шығарыўда'": "label: t('orders.status_production')",
    "label: 'Таяр (ОТК)'": "label: t('orders.status_ready')",
    "label: 'Орнатылды (Жабылды)'": "label: t('orders.status_closed')",
    "'Келисилген мүддет'": "t('orders.agreed_deadline')",
    "МЕБЕЛЬ ИСЛЕП ШЫҒАРЫЎ ҲӘМ ЖЕТКИЗИП БЕРИЎ ШӘРТНАМАСЫ": "${t('orders.contract_title')}",
    "Шәртнама Рақами:": "${t('orders.contract_number')}",
    "Нөкис қаласы": "${t('orders.city')}",
    "Сәне:": "${t('orders.date')}",
    "жыл<": "${t('orders.year')}<",
    "1. ШӘРТНАМА ТӘРЕПЛЕРИ": "${t('orders.parties_title')}",
    "Усы шәртнама Мебель ислеп шығарыў цехы атынан \"WOODFLOW\" ЖШЖ (кейинги орынларда \"Орынлаўшы\" деп аталады) ҳәм қрыйдар <strong>${selectedOrder.customerName}</strong> (кейинги орынларда \"Буйыртпашы\" деп аталады) арасында Өзбекстан Республикасы Пуқаралық Кодекси талапларына муўапық төмендеги шәртлер тийкарында дүзилди.": "${t('orders.parties_desc', { customerName: selectedOrder.customerName })}",
    "2. ШӘРТНАМА МАҚСЕТИ": "${t('orders.subject_title')}",
    "2.1. Орынлаўшы Буйыртпашы тәрепинен усынылған 3D жойбар сызбалары ҳәм киши Техникалық Тапсырма (Мини-ТТ) тийкарында мебель топламын сапалы таярлап бериў ҳәм орнатыў миннетлемесин алады.": "${t('orders.subject_desc1')}",
    "2.2. Бөлме өлшемлери: Узынлығы: ${selectedOrder.dimensions?.length || 3.0} м, Кеңлиги: ${selectedOrder.dimensions?.width || 2.5} м, Потолок бәлентлиги: ${selectedOrder.dimensions?.height || 2.7} м.": "${t('orders.subject_desc2', { length: selectedOrder.dimensions?.length || 3.0, width: selectedOrder.dimensions?.width || 2.5, height: selectedOrder.dimensions?.height || 2.7 })}",
    "3. ШӘРТНАМА СУММАСЫ ҲӘМ ТӨЛЕМ ТӘРТИБИ": "${t('orders.payment_title')}",
    "3.1. Шәртнаманың улыўма суммасы <strong>${selectedOrder.totalPrice.toLocaleString()} UZS</strong> етип белгиленди.": "${t('orders.payment_desc1', { totalPrice: selectedOrder.totalPrice.toLocaleString() })}",
    "3.2. Буйыртпашы шәртнамаға қол қойылған ўақытта жәми сумманың ${advancePercent}% проценти, яғный <strong>${selectedOrder.advancePayment.toLocaleString()} UZS</strong> муғдарында аванс төлемин әмелге асырады.": "${t('orders.payment_desc2', { advancePercent, advancePayment: selectedOrder.advancePayment.toLocaleString() })}",
    "3.3. Қалған төлем (күтилип атырған қалдық <strong>${(selectedOrder.totalPrice - selectedOrder.advancePayment).toLocaleString()} UZS</strong>) мебель орнатылып, сапа тексериўи (ОТК) тапсырылғаннан соң 3 банк күни ишинде төленеди.": "${t('orders.payment_desc3', { remaining: (selectedOrder.totalPrice - selectedOrder.advancePayment).toLocaleString() })}",
    "4. МҮДДЕТ ҲӘМ КЕШИГИЎ ЖӘРИЙМАСЫ (ПЕНЯ)": "${t('orders.penalty_title')}",
    "4.1. Орынлаўшы мебель өнимлерин <strong>${deadlineStr}</strong> мүддетке шекем таярлаўы ҳәм орнатып бериўи шәрт.": "${t('orders.penalty_desc1', { deadline: deadlineStr })}",
    "4.2. Егерде Орынлаўшы өз миннетлемелерин ўақтында орынламаса, ҳәр бир кешиктирилген күн ушын жәми шәртнама суммасының 0.1% проценти муғдарында пеня төлейди. Бирақ пеняның улыўма суммасы шәртнама баҳасының 10% инен асып кетпеўи керек.": "${t('orders.penalty_desc2')}",
    "5. КЕПИЛЛИК ШӘРТЛЕРИ": "${t('orders.warranty_title')}",
    "5.1. Орынлаўшы тапсырылған мебельлер ушын <strong>12 ай</strong> мүддетке кепиллик береди.": "${t('orders.warranty_desc1')}",
    "ОРЫНЛАЎШЫ:": "${t('orders.contractor')}",
    "БУЙЫРТПАШЫ:": "${t('orders.customer')}",
    "\"WOODFLOW\" ЖШЖ Мебель Цехы": "${t('orders.company_name')}",
    "Қол:": "${t('orders.signature')}",
    "Телефон:": "${t('orders.phone_label')}"
}

for (const [oldText, newText] of Object.entries(rep)) {
    content = content.split(oldText).join(newText);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log('Done rewriting component.');
